name: Stale Branches

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1'
    
permissions:
  issues: write
  contents: write

jobs:
  stale_branches:
    runs-on: ubuntu-latest
    steps:
    - name: Stale Branches
      uses: crs-k/stale-branches@v3.0.0
      with:
        repo-token: '${{ secrets.ADD_TO_PROJECT_PAT }}'
        days-before-stale: 20
        days-before-delete: 180
        comment-updates: true
        max-issues: 20
        tag-committer: true
        stale-branch-label: 'stale branch ğŸ—‘ï¸'
        compare-branches: 'info'
        branches-filter-regex: '^((?!dependabot))'
  check-if-issue-exists:
    runs-on: ubuntu-latest
    needs: [ stale_branches ]
    steps:
    - name: check_if_issue_exists
      uses: nickderobertis/check-if-issue-exists-action@master
      id: check_if_issue_exists
      with:
        repo: GSA/px-bears-drupal
        token: ${{ secrets.ADD_TO_PROJECT_PAT }}
        labels: 'stale branch ğŸ—‘ï¸'

    - name: Add comment
      if: steps.check_if_issue_exists.outputs.exists == 'true'
      uses: peter-evans/create-or-update-comment@v3
      with:
        repo-token: '${{ secrets.ADD_TO_PROJECT_PAT }}'
        repo: GSA/px-bears-drupal
        issue-number: ${{ github.event.issue.number }}
        body: |
          Hi @${{ env.TECH_LEAD }}, this issue is available for your review. Thank you for your help! :sparkles: