name: Run Cypress e2e Prod Nightly Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions: read-all

defaults:
  run:
    working-directory: ./benefit-finder

jobs:
  install:
    name: cypress-run-prod-e2e
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "./benefit-finder/package.json"

      - name: Cypress Run
        id: e2e
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          env: NODE_ENV=test
          config-file: cypress.prod.config.js
          working-directory: benefit-finder

      - name: create github issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          assignees: ${{ vars.TECH_LEAD }}, ${{ vars.CONTENT_LEAD }}
          title: "Nightly e2e Test(s) Fail"
          body: |
            ## Automated issue of Nightly e2e failure

            <details><summary>Show Errors</summary>

            `${{ steps.e2e.outcome }}`

            </details>
