---
  name: Benefit-finder uswds version sync
  
  on:
      workflow_dispatch:
  # It will run at 6 AM on Modays
      schedule:
          - cron: '0 6 * * 1'
  
  jobs:
      uswds-version-check:
          runs-on: ubuntu-latest
          steps:   
              - name: Cloning the Repo and initiating the Submodule
                env:
                  GITHUB_TOKEN: '${{ secrets.ADD_TO_PROJECT_PAT }}'
                run: |
                  echo "cloning the repo and initiating the usagov-2021 submodule"
                  gh repo clone GSA/px-bears-drupal
                  cd px-bears-drupal
                  git submodule init
                  git submodule update
              - name: Run the script
                env:
                  GITHUB_TOKEN: '${{ secrets.ADD_TO_PROJECT_PAT }}'
                run: |
                  cd px-bears-drupal/bin
                  bash check-uswds-version.sh
              - name: Create Pull Request
                env:
                  GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
                  Tech_lead: ${{ vars.TECH_LEAD }}
                uses: peter-evans/create-pull-request@v5
                with:
                  path: "px-bears-drupal"
                  token: ${{ secrets.ADD_TO_PROJECT_PAT }}
                  commit-message: Update USDWS version
                  committer: GitHub <noreply@github.com>
                  author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
                  signoff: false
                  title: '[USDWS Version Sync] - Version Update'
                  body: |
                    Update report
                    - This PR is for ${{ env.Tech_lead }} to review.
                    - Auto-generated by [create-pull-request][1]
      
                    [1]: https://github.com/peter-evans/create-pull-request
                  labels: |
                    USDWS version sync
                    automated pr
                  assignees: ${{ env.Tech_lead }}
                  reviewers: ${{ env.Tech_lead }}
  